/** @format */

import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata, Viewport } from "next";
import type { CSSProperties, ReactNode } from "react";
import { AppApolloProvider } from "@/components/providers/apollo-provider";
import "./globals.css";
import "@fontsource/google-sans";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="h-full antialiased">
        <body
          className="flex min-h-screen flex-col"
          style={{
            fontFamily: "Google Sans",
            letterSpacing: "1px",
          }}
        >
          <AppApolloProvider>{children}</AppApolloProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
