/** @format */

import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import type { CSSProperties, ReactNode } from "react";
import { AppApolloProvider } from "@/components/providers/apollo-provider";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html
				lang="en"
				className="h-full antialiased"
				style={
					{
						"--font-geist-sans":
							"ui-sans-serif, -apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif",
						"--font-geist-mono":
							"ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, monospace",
					} as CSSProperties
				}
			>
				<body className="flex min-h-screen flex-col">
					<AppApolloProvider>{children}</AppApolloProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
