import type { Question } from "./types";

export const mockQuestions: Question[] = [
  {
    id: "q-001",
    title: "Квадрат тэгшитгэлийн язгуур олох",
    content:
      "x² - 5x + 6 = 0 тэгшитгэлийг бодоод, гарсан язгууруудыг графиктай холбон тайлбарла.",
    type: "short_answer",
    subject: "Math",
    topic: "Алгебр",
    gradeLevel: "9-р анги",
    difficulty: "Easy",
    skillTag: "Logic",
    usageCount: 18,
    correctRate: 76,
    createdBy: "Н. Энхмаа",
    lastUsedAt: "2026-03-10",
    status: "Active",
  },
  {
    id: "q-002",
    title: "Ньютоны 2-р хуулийн бодит хэрэглээ",
    content:
      "F = ma хуулийг өдөр тутмын амьдралын нэг жишээгээр тайлбарлаж, тооцоотой бодлого бод.",
    type: "essay",
    subject: "Physics",
    topic: "Механик",
    gradeLevel: "10-р анги",
    difficulty: "Medium",
    skillTag: "Analysis",
    usageCount: 23,
    correctRate: 47,
    createdBy: "Б. Түвшин",
    lastUsedAt: "2026-03-18",
    status: "Active",
  },
  {
    id: "q-003",
    title: "Хүчил-суурийн саармагжих урвал",
    content:
      "Давсны хүчил ба натрийн гидроксид урвалд ороход ямар бүтээгдэхүүн үүсэх вэ? Урвалыг тэнцүүл.",
    type: "multiple_choice",
    subject: "Chemistry",
    topic: "Химийн урвал",
    gradeLevel: "9-р анги",
    difficulty: "Easy",
    skillTag: "Memory",
    usageCount: 31,
    correctRate: 36,
    createdBy: "С. Ариунаа",
    lastUsedAt: "2026-03-20",
    status: "Active",
  },
  {
    id: "q-004",
    title: "Эхийн гол санааг тодорхойлох",
    content:
      "Өгөгдсөн эхийг уншаад гол санаа болон дэмжих хоёр санааг тодорхойлж бич.",
    type: "short_answer",
    subject: "English",
    topic: "Уншиж ойлгох",
    gradeLevel: "8-р анги",
    difficulty: "Medium",
    skillTag: "Analysis",
    usageCount: 12,
    correctRate: 69,
    createdBy: "Д. Мөнхзул",
    lastUsedAt: "2026-03-01",
    status: "Active",
  },
  {
    id: "q-005",
    title: "Пифагорын теоремын хэрэглээ",
    content: "10м шат ханыг 6м зайтай тулсан бол хүрэх өндрийг ол.",
    type: "multiple_choice",
    subject: "Math",
    topic: "Геометр",
    gradeLevel: "8-р анги",
    difficulty: "Easy",
    skillTag: "Problem Solving",
    usageCount: 26,
    correctRate: 82,
    createdBy: "Н. Энхмаа",
    lastUsedAt: "2026-03-22",
    status: "Active",
  },
  {
    id: "q-006",
    title: "Импульс хадгалагдах хууль",
    content:
      "Хоёр тэрэг мөргөлдөх үед импульс хадгалагдах хуулиар эцсийн хурдыг олж тайлбарла.",
    type: "essay",
    subject: "Physics",
    topic: "Импульс",
    gradeLevel: "11-р анги",
    difficulty: "Hard",
    skillTag: "Problem Solving",
    usageCount: 8,
    correctRate: 33,
    createdBy: "Б. Түвшин",
    lastUsedAt: "2026-02-20",
    status: "Draft",
  },
  {
    id: "q-007",
    title: "Үелэх хүснэгтийн чиг хандлага",
    content:
      "3-р үеийн атомын радиус болон цахилгаан сөрөг чанарын өөрчлөлтийг тайлбарла.",
    type: "short_answer",
    subject: "Chemistry",
    topic: "Үелэх хүснэгт",
    gradeLevel: "10-р анги",
    difficulty: "Medium",
    skillTag: "Analysis",
    usageCount: 16,
    correctRate: 58,
    createdBy: "С. Ариунаа",
    lastUsedAt: "2026-03-03",
    status: "Active",
  },
  {
    id: "q-008",
    title: "Нөхцөлт өгүүлбэрийн хэрэглээ",
    content:
      "Өгүүлбэр бүрт зөв нөхцөлт хэлбэрийг сонгож, нэг хариултаа тайлбарлан бич.",
    type: "multiple_choice",
    subject: "English",
    topic: "Дүрэм",
    gradeLevel: "9-р анги",
    difficulty: "Easy",
    skillTag: "Memory",
    usageCount: 30,
    correctRate: 84,
    createdBy: "Д. Мөнхзул",
    lastUsedAt: "2026-03-19",
    status: "Active",
  },
  {
    id: "q-009",
    title: "Тэнцэтгэл бишийн бодлого",
    content:
      "Өдөр тутмын худалдан авалтын нөхцөл дээр тулгуурлан тэнцэтгэл биш байгуулж бод.",
    type: "essay",
    subject: "Math",
    topic: "Тэнцэтгэл биш",
    gradeLevel: "10-р анги",
    difficulty: "Hard",
    skillTag: "Problem Solving",
    usageCount: 14,
    correctRate: 42,
    createdBy: "Н. Энхмаа",
    lastUsedAt: "2026-01-30",
    status: "Active",
  },
  {
    id: "q-010",
    title: "Цахилгаан хэлхээний шинжилгээ",
    content:
      "Хэлхээний схемээс гүйдлийн чиглэл болон эквивалент эсэргүүцлийг тодорхойл.",
    type: "short_answer",
    subject: "Physics",
    topic: "Цахилгаан",
    gradeLevel: "11-р анги",
    difficulty: "Medium",
    skillTag: "Logic",
    usageCount: 27,
    correctRate: 35,
    createdBy: "Б. Түвшин",
    lastUsedAt: "2026-03-11",
    status: "Active",
  },
  {
    id: "q-011",
    title: "Урвалын хурданд нөлөөлөх хүчин зүйл",
    content:
      "Температур ба концентраци урвалын хурдад хэрхэн нөлөөлөхийг туршилтын жишээгээр тайлбарла.",
    type: "essay",
    subject: "Chemistry",
    topic: "Кинетик",
    gradeLevel: "11-р анги",
    difficulty: "Hard",
    skillTag: "Analysis",
    usageCount: 6,
    correctRate: 53,
    createdBy: "С. Ариунаа",
    lastUsedAt: "2025-12-14",
    status: "Draft",
  },
  {
    id: "q-012",
    title: "Үгийн утгыг өгүүлбэрээс таах",
    content:
      "Өгүүлбэрийн нөхцөлөөс тэмдэглэсэн үгсийн утгыг тодорхойлж тайлбарла.",
    type: "short_answer",
    subject: "English",
    topic: "Үгийн сан",
    gradeLevel: "8-р анги",
    difficulty: "Easy",
    skillTag: "Logic",
    usageCount: 21,
    correctRate: 78,
    createdBy: "Д. Мөнхзул",
    lastUsedAt: "2026-03-15",
    status: "Active",
  },
  {
    id: "q-013",
    title: "Шулуун функцийн график",
    content:
      "y = 2x - 3 функцийг графиклаж, налалт болон y-тэнхлэгтэй огтлолцлыг ол.",
    type: "multiple_choice",
    subject: "Math",
    topic: "Шугаман функц",
    gradeLevel: "8-р анги",
    difficulty: "Easy",
    skillTag: "Memory",
    usageCount: 34,
    correctRate: 92,
    createdBy: "Н. Энхмаа",
    lastUsedAt: "2026-03-24",
    status: "Active",
  },
  {
    id: "q-014",
    title: "Энергийн хувирал",
    content:
      "Дүүжин савлуурын хөдөлгөөн дээр потенциал ба кинетик энергийн хувирлыг тайлбарла.",
    type: "essay",
    subject: "Physics",
    topic: "Энерги",
    gradeLevel: "9-р анги",
    difficulty: "Medium",
    skillTag: "Analysis",
    usageCount: 25,
    correctRate: 48,
    createdBy: "Б. Түвшин",
    lastUsedAt: "2026-02-26",
    status: "Archived",
  },
  {
    id: "q-015",
    title: "Органик ба органик бус нэгдэл",
    content:
      "Органик болон органик бус нэгдлийг хоёр хоёр жишээгээр ялгаж тайлбарла.",
    type: "short_answer",
    subject: "Chemistry",
    topic: "Органик хими",
    gradeLevel: "10-р анги",
    difficulty: "Medium",
    skillTag: "Memory",
    usageCount: 15,
    correctRate: 64,
    createdBy: "С. Ариунаа",
    lastUsedAt: "2026-01-18",
    status: "Active",
  },
  {
    id: "q-016",
    title: "Маргаантай догол мөр бичих",
    content:
      "Сургуулийн дүрэмт хувцасны талаар баримт, тайлбар, дүгнэлттэй догол мөр бич.",
    type: "essay",
    subject: "English",
    topic: "Бичих чадвар",
    gradeLevel: "10-р анги",
    difficulty: "Hard",
    skillTag: "Problem Solving",
    usageCount: 9,
    correctRate: 44,
    createdBy: "Д. Мөнхзул",
    lastUsedAt: "2026-02-10",
    status: "Draft",
  },
  {
    id: "q-017",
    title: "Нийлмэл үйл явдлын магадлал",
    content: "Уутнаас буцааж хийхгүйгээр 2 удаа авах магадлалыг ол.",
    type: "short_answer",
    subject: "Math",
    topic: "Магадлал",
    gradeLevel: "11-р анги",
    difficulty: "Hard",
    skillTag: "Logic",
    usageCount: 22,
    correctRate: 39,
    createdBy: "Н. Энхмаа",
    lastUsedAt: "2026-03-04",
    status: "Active",
  },
  {
    id: "q-018",
    title: "Долгионы үндсэн шинж",
    content:
      "Давтамж, долгионы урт, далайцын тодорхойлолтыг зөв харгалзуулж тайлбарла.",
    type: "multiple_choice",
    subject: "Physics",
    topic: "Долгион",
    gradeLevel: "9-р анги",
    difficulty: "Easy",
    skillTag: "Memory",
    usageCount: 24,
    correctRate: 72,
    createdBy: "Б. Түвшин",
    lastUsedAt: "2026-03-02",
    status: "Active",
  },
  {
    id: "q-019",
    title: "Стехиометрийн массын тооцоо",
    content: "Өгөгдсөн реагентаас үүсэх бүтээгдэхүүний массыг бодож ол.",
    type: "short_answer",
    subject: "Chemistry",
    topic: "Стехиометр",
    gradeLevel: "11-р анги",
    difficulty: "Hard",
    skillTag: "Problem Solving",
    usageCount: 19,
    correctRate: 37,
    createdBy: "С. Ариунаа",
    lastUsedAt: "2026-03-07",
    status: "Active",
  },
  {
    id: "q-020",
    title: "Эхийн өнгө аяс, мэдрэмж",
    content:
      "Өгүүлбэрийн сонголтоор tone ба mood-ийг тодорхойлж, шалтгаанаа бич.",
    type: "short_answer",
    subject: "English",
    topic: "Уран зохиол",
    gradeLevel: "10-р анги",
    difficulty: "Medium",
    skillTag: "Analysis",
    usageCount: 26,
    correctRate: 49,
    createdBy: "Д. Мөнхзул",
    lastUsedAt: "2026-03-05",
    status: "Archived",
  },
  {
    id: "q-021",
    title: "Тригонометрийн харьцаа",
    content:
      "Баруун өнцөгт гурвалжны өгөгдсөн талуудаас sin, cos, tan утгыг ол.",
    type: "multiple_choice",
    subject: "Math",
    topic: "Тригонометр",
    gradeLevel: "10-р анги",
    difficulty: "Medium",
    skillTag: "Problem Solving",
    usageCount: 7,
    correctRate: 67,
    createdBy: "Н. Энхмаа",
    lastUsedAt: "2026-03-06",
    status: "Active",
  },
  {
    id: "q-022",
    title: "Химийн холбооны төрөл",
    content:
      "Ион, ковалент, металл холбооны ялгааг бодит бодисын жишээгээр тайлбарла.",
    type: "essay",
    subject: "Chemistry",
    topic: "Химийн холбоо",
    gradeLevel: "9-р анги",
    difficulty: "Medium",
    skillTag: "Analysis",
    usageCount: 5,
    correctRate: 56,
    createdBy: "С. Ариунаа",
    lastUsedAt: "2026-03-09",
    status: "Active",
  },
];
