import type { Question, QuestionFilters } from "./types";
import { renderFormulaPreview } from "./utils";

export const QUESTION_BANK_FILTER_DEFAULTS: QuestionFilters = {
  search: "",
  questionType: "all",
  difficulty: "all",
  subject: "all",
  grade: "all",
  subtopic: "all",
  status: "all",
  sortBy: "newest",
};

export const SUBJECT_OPTIONS = [
  "Математик",
  "Хими",
  "Физик",
  "Биологи",
  "Англи хэл",
  "Бусад хичээл",
] as const;

export const SUBTOPIC_OPTIONS: Record<(typeof SUBJECT_OPTIONS)[number], string[]> = {
  "Математик": ["Алгебр", "Геометр", "Тригонометр", "Магадлал", "Статистик"],
  "Хими": ["Ерөнхий хими", "Органик хими", "Аналитик хими", "Физик хими"],
  "Физик": ["Кинематик", "Динамик", "Дулаан", "Цахилгаан", "Оптик"],
  "Биологи": ["Эс судлал", "Генетик", "Экологи", "Хүний биологи"],
  "Англи хэл": ["Грамматик", "Уншлага", "Сонсгол", "Бичгийн чадвар"],
  "Бусад хичээл": ["Ерөнхий"],
};

export const GRADE_OPTIONS = [
  "6-р анги",
  "7-р анги",
  "8-р анги",
  "9-р анги",
  "10-р анги",
  "11-р анги",
  "12-р анги",
] as const;

export const EXAM_DESTINATIONS = [
  "Явцын шалгалт",
  "STEM долоо хоногийн сорил",
  "Эцсийн шалгалтын бүтээгч",
  "Дадлагын тестийн багц",
] as const;

export const MOCK_QUESTIONS: Question[] = [
  {
    id: "qb-001",
    title: "Квадрат тэгшитгэлийн язгуур олох",
    questionType: "multiple_choice",
    content: {
      prompt: "x^2 - 5x + 6 = 0 тэгшитгэлийн язгуур аль нь вэ?",
      guidance: "Хамгийн зөв хариултыг сонгоно уу.",
      explanation: "Алгебрын явцын шалгалтад тохиромжтой.",
    },
    options: [
      { id: "a", text: "x = 2 ба x = 3", isCorrect: true },
      { id: "b", text: "x = -2 ба x = -3", isCorrect: false },
      { id: "c", text: "x = 1 ба x = 6", isCorrect: false },
      { id: "d", text: "x = 0 ба x = 5", isCorrect: false },
    ],
    correctAnswer: "x = 2 ба x = 3",
    rubric: "",
    formulaRaw: "",
    formulaPreview: "",
    imageUrl: "",
    fileUploadConfig: {
      acceptedFileTypes: [],
      instructions: "",
      maxFiles: 0,
    },
    subject: "Математик",
    grade: "9-р анги",
    subtopic: "Алгебр",
    difficulty: "easy",
    points: 2,
    status: "published",
    gradingType: "auto",
    usageCount: 24,
    createdAt: "2026-03-20T10:00:00.000Z",
    updatedAt: "2026-03-24T08:15:00.000Z",
  },
  {
    id: "qb-002",
    title: "Фотосинтезийн богино хариулт",
    questionType: "short_answer",
    content: {
      prompt: "Фотосинтезд оролцдог үндсэн пигментийг нэрлэнэ үү.",
      guidance: "Нэг эсвэл хоёр үгээр хариулахад хангалттай.",
      explanation: "Биологийн богино мэдлэг шалгалтад тохиромжтой.",
    },
    options: [],
    correctAnswer: "Хлорофилл",
    rubric: "",
    formulaRaw: "",
    formulaPreview: "",
    imageUrl: "",
    fileUploadConfig: {
      acceptedFileTypes: [],
      instructions: "",
      maxFiles: 0,
    },
    subject: "Биологи",
    grade: "8-р анги",
    subtopic: "Эс судлал",
    difficulty: "easy",
    points: 1,
    status: "published",
    gradingType: "hybrid",
    usageCount: 18,
    createdAt: "2026-03-18T11:00:00.000Z",
    updatedAt: "2026-03-21T09:40:00.000Z",
  },
  {
    id: "qb-003",
    title: "Кинематикийн тайлбар хийх",
    questionType: "long_answer",
    content: {
      prompt: "Амьдрал дээрх хөдөлгөөний жишээгээр хурд ба хурдатгалын ялгааг тайлбарлана уу.",
      guidance: "Өдөр тутмын бодит жишээ ашиглаарай.",
      explanation: "Ойлголтын гүнзгий түвшинг гараар үнэлнэ.",
    },
    options: [],
    correctAnswer: "",
    rubric: "Ялгааг зөв тайлбарлаж, бодит жишээ хавсаргавал бүтэн оноо өгнө. Нэг ойлголт зөв бол хэсэгчилсэн оноо өгнө.",
    formulaRaw: "",
    formulaPreview: "",
    imageUrl: "",
    fileUploadConfig: {
      acceptedFileTypes: [],
      instructions: "",
      maxFiles: 0,
    },
    subject: "Физик",
    grade: "10-р анги",
    subtopic: "Кинематик",
    difficulty: "medium",
    points: 8,
    status: "draft",
    gradingType: "manual",
    usageCount: 6,
    createdAt: "2026-03-16T10:20:00.000Z",
    updatedAt: "2026-03-23T14:05:00.000Z",
  },
  {
    id: "qb-004",
    title: "Тригонометр илэрхийллийн уламжлал олох",
    questionType: "formula_input",
    content: {
      prompt: "y = sin(x^2) функцийн уламжлалыг олно уу.",
      guidance: "Гинжин дүрмийн тэмдэглэгээг ашиглана уу.",
      explanation: "Тэмдэглэгээтэй томьёоны хариулт дадлага хийхэд тохиромжтой.",
    },
    options: [],
    correctAnswer: "2xcos(x^2)",
    rubric: "",
    formulaRaw: "\\frac{d}{dx} \\sin(x^2) = 2x\\cos(x^2)",
    formulaPreview: renderFormulaPreview("\\frac{d}{dx} \\sin(x^2) = 2x\\cos(x^2)"),
    imageUrl: "",
    fileUploadConfig: {
      acceptedFileTypes: [],
      instructions: "",
      maxFiles: 0,
    },
    subject: "Математик",
    grade: "11-р анги",
    subtopic: "Тригонометр",
    difficulty: "hard",
    points: 5,
    status: "published",
    gradingType: "hybrid",
    usageCount: 14,
    createdAt: "2026-03-14T08:00:00.000Z",
    updatedAt: "2026-03-25T08:45:00.000Z",
  },
  {
    id: "qb-005",
    title: "Эсийн бүтцийг нэрлэх",
    questionType: "image_based",
    content: {
      prompt: "Зургийг ажиглаад улаанаар тэмдэглэсэн эрхтэнцрийг нэрлэнэ үү.",
      guidance: "Хариултын талбарт эрхтэнцрийн нэрийг бичнэ үү.",
      explanation: "Диаграммд суурилсан сэргээн санах асуултад тохиромжтой.",
    },
    options: [],
    correctAnswer: "",
    rubric: "Зөв хариулт нь цөм. Бага зэргийн зөв бичгийн алдааг зөвшөөрнө.",
    formulaRaw: "",
    formulaPreview: "",
    imageUrl:
      "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=1200&q=80",
    fileUploadConfig: {
      acceptedFileTypes: [],
      instructions: "",
      maxFiles: 0,
    },
    subject: "Биологи",
    grade: "7-р анги",
    subtopic: "Хүний биологи",
    difficulty: "medium",
    points: 4,
    status: "published",
    gradingType: "manual",
    usageCount: 9,
    createdAt: "2026-03-13T12:15:00.000Z",
    updatedAt: "2026-03-25T09:20:00.000Z",
  },
  {
    id: "qb-006",
    title: "Уран зохиолын задлан шинжилгээний бичвэр хавсаргах",
    questionType: "file_upload",
    content: {
      prompt: "Сонгосон эхийн өгүүлэгчийн өнгө аясыг задлан шинжилсэн нэг нүүр бичвэрээ хавсаргана уу.",
      guidance: "PDF эсвэл DOCX хэлбэрээр хүлээн авна.",
      explanation: "Урт бичгийн даалгаварт тохиромжтой.",
    },
    options: [],
    correctAnswer: "",
    rubric: "Гол санааны тодорхой байдал, эшлэлийн хэрэглээ, тайлбарын чанарыг үнэлнэ.",
    formulaRaw: "",
    formulaPreview: "",
    imageUrl: "",
    fileUploadConfig: {
      acceptedFileTypes: [".pdf", ".docx"],
      instructions: "Бичвэр болон нотлох эшлэлээ нэг файл болгон хавсаргана уу.",
      maxFiles: 1,
    },
    subject: "Англи хэл",
    grade: "12-р анги",
    subtopic: "Бичгийн чадвар",
    difficulty: "hard",
    points: 10,
    status: "draft",
    gradingType: "manual",
    usageCount: 3,
    createdAt: "2026-03-11T15:00:00.000Z",
    updatedAt: "2026-03-24T16:10:00.000Z",
  },
];
