import type { Question, QuestionFilters } from "./types";
import { renderFormulaPreview } from "./utils";

export const QUESTION_BANK_FILTER_DEFAULTS: QuestionFilters = {
  search: "",
  questionType: "all",
  difficulty: "all",
  subject: "all",
  grade: "all",
  topic: "all",
  subtopic: "all",
  status: "all",
  sortBy: "newest",
};

export const SUBJECT_OPTIONS = [
  "Математик",
  "Хими",
  "Физик",
  "Биологи",
  "Англи хэл",
  "Бусад хичээл",
] as const;

export const GRADE_OPTIONS = [
  "4-р анги",
  "5-р анги",
  "6-р анги",
  "7-р анги",
  "8-р анги",
  "9-р анги",
  "10-р анги",
  "11-р анги",
  "12-р анги",
] as const;

export const SUBTOPIC_OPTIONS: Record<(typeof SUBJECT_OPTIONS)[number], string[]> = {
  "Математик": ["Алгебр", "Геометр", "Тригонометр", "Магадлал", "Статистик"],
  "Хими": ["Ерөнхий хими", "Органик хими", "Аналитик хими", "Физик хими"],
  "Физик": ["Кинематик", "Динамик", "Дулаан", "Цахилгаан", "Оптик"],
  "Биологи": ["Эс судлал", "Генетик", "Экологи", "Хүний биологи"],
  "Англи хэл": ["Грамматик", "Уншлага", "Сонсгол", "Бичгийн чадвар"],
  "Бусад хичээл": ["Ерөнхий"],
};

export const EXAM_DESTINATIONS = [
  "Явцын шалгалт",
  "STEM долоо хоногийн сорил",
  "Эцсийн шалгалтын бүтээгч",
  "Дадлагын тестийн багц",
] as const;

export const MOCK_QUESTIONS: Question[] = [
  {
    id: "qb-001",
    title: "Квадрат тэгшитгэлийн язгуур олох",
    questionType: "multiple_choice",
    content: {
      prompt: "x^2 - 5x + 6 = 0 тэгшитгэлийн язгуур аль нь вэ?",
      guidance: "Хамгийн зөв хариултыг сонгоно уу.",
      explanation: "10-р ангийн алгебрын явцын шалгалтад тохиромжтой.",
    },
    options: [
      { id: "a", text: "x = 2 ба x = 3", isCorrect: true },
      { id: "b", text: "x = -2 ба x = -3", isCorrect: false },
      { id: "c", text: "x = 1 ба x = 6", isCorrect: false },
      { id: "d", text: "x = 0 ба x = 5", isCorrect: false },
    ],
    correctAnswer: "x = 2 ба x = 3",
    rubric: "",
    formulaRaw: "",
    formulaPreview: "",
    imageUrl: "",
    fileUploadConfig: {
      acceptedFileTypes: [],
      instructions: "",
      maxFiles: 0,
    },
    grade: "10-р анги",
    subject: "Математик",
    topic: "Квадрат тэгшитгэл",
    difficulty: "easy",
    points: 2,
    status: "published",
    gradingType: "auto",
    usageCount: 24,
    createdAt: "2026-03-20T10:00:00.000Z",
    updatedAt: "2026-03-24T08:15:00.000Z",
  },
  {
    id: "qb-002",
    title: "Функцийн тодорхойлолтын муж олох",
    questionType: "short_answer",
    content: {
      prompt: "f(x) = 1 / (x - 4) функцийн тодорхойлолтын мужаас хасагдах утгыг нэрлэнэ үү.",
      guidance: "Нэг тоогоор хариулахад хангалттай.",
      explanation: "10-р ангийн функц сэдвийн богино хариултын асуулт.",
    },
    options: [],
    correctAnswer: "4",
    rubric: "",
    formulaRaw: "",
    formulaPreview: "",
    imageUrl: "",
    fileUploadConfig: {
      acceptedFileTypes: [],
      instructions: "",
      maxFiles: 0,
    },
    grade: "10-р анги",
    subject: "Математик",
    topic: "Функц",
    difficulty: "easy",
    points: 1,
    status: "published",
    gradingType: "hybrid",
    usageCount: 18,
    createdAt: "2026-03-18T11:00:00.000Z",
    updatedAt: "2026-03-21T09:40:00.000Z",
  },
  {
    id: "qb-003",
    title: "Функцийн графикийн шилжилт тайлбарлах",
    questionType: "long_answer",
    content: {
      prompt: "y = x^2 графикийг y = (x - 2)^2 + 3 болгон хувиргахад ямар шилжилт хийгдэхийг тайлбарлана уу.",
      guidance: "Хэвтээ болон босоо шилжилтийг тусад нь тайлбарлаарай.",
      explanation: "10-р ангийн функцийн ойлголтын гүнзгий түвшинг гараар үнэлнэ.",
    },
    options: [],
    correctAnswer: "",
    rubric: "Баруун тийш 2 нэгж, дээш 3 нэгж шилжсэн гэж зөв тайлбарлавал бүтэн оноо өгнө. Нэг шилжилтийг зөв тайлбарлавал хэсэгчилсэн оноо өгнө.",
    formulaRaw: "",
    formulaPreview: "",
    imageUrl: "",
    fileUploadConfig: {
      acceptedFileTypes: [],
      instructions: "",
      maxFiles: 0,
    },
    grade: "10-р анги",
    subject: "Математик",
    topic: "Функцийн график",
    difficulty: "medium",
    points: 8,
    status: "draft",
    gradingType: "manual",
    usageCount: 6,
    createdAt: "2026-03-16T10:20:00.000Z",
    updatedAt: "2026-03-23T14:05:00.000Z",
  },
  {
    id: "qb-004",
    title: "Тригонометр илэрхийллийн уламжлал олох",
    questionType: "formula_input",
    content: {
      prompt: "y = sin(x^2) функцийн уламжлалыг олно уу.",
      guidance: "Гинжин дүрмийн тэмдэглэгээг ашиглана уу.",
      explanation: "10-р ангийн гүнзгийрүүлсэн математикийн томьёоны дасгалд тохиромжтой.",
    },
    options: [],
    correctAnswer: "2xcos(x^2)",
    rubric: "",
    formulaRaw: "\\frac{d}{dx} \\sin(x^2) = 2x\\cos(x^2)",
    formulaPreview: renderFormulaPreview("\\frac{d}{dx} \\sin(x^2) = 2x\\cos(x^2)"),
    imageUrl: "",
    fileUploadConfig: {
      acceptedFileTypes: [],
      instructions: "",
      maxFiles: 0,
    },
    grade: "10-р анги",
    subject: "Математик",
    topic: "Тригонометр",
    difficulty: "hard",
    points: 5,
    status: "published",
    gradingType: "hybrid",
    usageCount: 14,
    createdAt: "2026-03-14T08:00:00.000Z",
    updatedAt: "2026-03-25T08:45:00.000Z",
  },
  {
    id: "qb-005",
    title: "Графикаас функцийн утга унших",
    questionType: "image_based",
    content: {
      prompt: "Параболын графикийг ажиглаад x = 1 үед y-ийн утгыг нэрлэнэ үү.",
      guidance: "Зургийн дагуу координатыг анхааралтай уншаарай.",
      explanation: "10-р ангийн график унших чадварыг шалгах зурагт суурилсан асуулт.",
    },
    options: [],
    correctAnswer: "",
    rubric: "Графикаас зөв утга уншиж бичвэл бүтэн оноо өгнө.",
    formulaRaw: "",
    formulaPreview: "",
    imageUrl:
      "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=1200&q=80",
    fileUploadConfig: {
      acceptedFileTypes: [],
      instructions: "",
      maxFiles: 0,
    },
    grade: "10-р анги",
    subject: "Математик",
    topic: "Функцийн график",
    difficulty: "medium",
    points: 4,
    status: "published",
    gradingType: "manual",
    usageCount: 9,
    createdAt: "2026-03-13T12:15:00.000Z",
    updatedAt: "2026-03-25T09:20:00.000Z",
  },
  {
    id: "qb-006",
    title: "Статистикийн тайлан файл хавсаргах",
    questionType: "file_upload",
    content: {
      prompt: "Өгөгдсөн хүснэгтийн мэдээллээр дундаж, медиан, моодыг бодсон тайлангаа файл хэлбэрээр хавсаргана уу.",
      guidance: "PDF эсвэл DOCX хэлбэрээр хүлээн авна.",
      explanation: "10-р ангийн статистикийн задгай даалгаварт тохиромжтой.",
    },
    options: [],
    correctAnswer: "",
    rubric: "Дундаж, медиан, моодыг зөв бодож, тайлбарласан бол бүтэн оноо өгнө.",
    formulaRaw: "",
    formulaPreview: "",
    imageUrl: "",
    fileUploadConfig: {
      acceptedFileTypes: [".pdf", ".docx"],
      instructions: "Бодолт болон тайлбараа нэг файл болгон хавсаргана уу.",
      maxFiles: 1,
    },
    grade: "10-р анги",
    subject: "Математик",
    topic: "Статистик",
    difficulty: "hard",
    points: 10,
    status: "draft",
    gradingType: "manual",
    usageCount: 3,
    createdAt: "2026-03-11T15:00:00.000Z",
    updatedAt: "2026-03-24T16:10:00.000Z",
  },
  {
    id: "qb-007",
    title: "Квадрат функцийн оройг олох",
    questionType: "multiple_choice",
    content: {
      prompt: "y = x^2 - 6x + 5 функцийн оройн координат аль нь вэ?",
      guidance: "Хамгийн зөв хариултыг сонгоно уу.",
      explanation: "10-р ангийн квадрат функцийн хурдан шалгалтад тохиромжтой.",
    },
    options: [
      { id: "a", text: "(3, -4)", isCorrect: true },
      { id: "b", text: "(3, 4)", isCorrect: false },
      { id: "c", text: "(-3, -4)", isCorrect: false },
      { id: "d", text: "(6, 5)", isCorrect: false },
    ],
    correctAnswer: "(3, -4)",
    rubric: "",
    formulaRaw: "",
    formulaPreview: "",
    imageUrl: "",
    fileUploadConfig: {
      acceptedFileTypes: [],
      instructions: "",
      maxFiles: 0,
    },
    grade: "10-р анги",
    subject: "Математик",
    topic: "Квадрат функц",
    difficulty: "easy",
    points: 2,
    status: "published",
    gradingType: "auto",
    usageCount: 31,
    createdAt: "2026-03-22T09:30:00.000Z",
    updatedAt: "2026-03-25T11:15:00.000Z",
  },
  {
    id: "qb-008",
    title: "Логарифмын утга олох",
    questionType: "short_answer",
    content: {
      prompt: "log₂8-ийн утгыг олно уу.",
      guidance: "Зөвхөн тоон хариу бичээрэй.",
      explanation: "10-р ангийн логарифмын суурь ойлголтыг шалгах богино асуулт.",
    },
    options: [],
    correctAnswer: "3",
    rubric: "",
    formulaRaw: "",
    formulaPreview: "",
    imageUrl: "",
    fileUploadConfig: {
      acceptedFileTypes: [],
      instructions: "",
      maxFiles: 0,
    },
    grade: "10-р анги",
    subject: "Математик",
    topic: "Логарифм",
    difficulty: "medium",
    points: 3,
    status: "published",
    gradingType: "hybrid",
    usageCount: 19,
    createdAt: "2026-03-21T10:45:00.000Z",
    updatedAt: "2026-03-25T13:05:00.000Z",
  },
  {
    id: "qb-009",
    title: "Магадлалын өгүүлбэртэй бодлого",
    questionType: "long_answer",
    content: {
      prompt: "Нэг хайрцагт 5 улаан, 3 цэнхэр, 2 ногоон бөмбөг байв. Санамсаргүйгээр нэг бөмбөг авахад улаан эсвэл цэнхэр байх магадлалыг олж, бодолтоо тайлбарлана уу.",
      guidance: "Тааламжтай тохиолдол болон нийт тохиолдлыг тусад нь бичээрэй.",
      explanation: "10-р ангийн магадлалын бодолтыг тайлбарлан бичих чадварыг шалгана.",
    },
    options: [],
    correctAnswer: "",
    rubric: "8/10 эсвэл 4/5 гэж зөв гаргаж, бодолтоо ойлгомжтой тайлбарлавал бүтэн оноо өгнө.",
    formulaRaw: "",
    formulaPreview: "",
    imageUrl: "",
    fileUploadConfig: {
      acceptedFileTypes: [],
      instructions: "",
      maxFiles: 0,
    },
    grade: "10-р анги",
    subject: "Математик",
    topic: "Магадлал",
    difficulty: "medium",
    points: 5,
    status: "published",
    gradingType: "manual",
    usageCount: 12,
    createdAt: "2026-03-19T14:00:00.000Z",
    updatedAt: "2026-03-24T18:20:00.000Z",
  },
];
