import { notFound } from "next/navigation";
import type { ExamDetail } from "../_types/exam";

const examDetails: Record<string, ExamDetail> = {
  "exam-201": {
    id: "exam-201",
    title: "Алгебр I улирал",
    subject: "Математик",
    status: "scheduled",
    className: "10A",
    teacherName: "Б.Эрдэнэ",
    date: "2026-03-29",
    startTime: "09:00",
    endTime: "09:40",
    durationMinutes: 40,
    room: "203",
    examType: "Холимог",
    totalScore: 40,
    studentCount: 38,
    submittedCount: 0,
    notStartedCount: 38,
    questionCount: 20,
    multipleChoiceCount: 15,
    essayCount: 5,
    autoGradedCount: 15,
    manualReviewCount: 5,
    autoGradingStatus: "Бэлэн",
    manualGradingStatus: "Хүлээгдэж буй",
    finalResultStatus: "Ноорог",
    notes: [
      { id: "n-1", type: "warning", text: "Өрөө баталгаажаагүй" },
      {
        id: "n-2",
        type: "warning",
        text: "Өөр шалгалттай цаг ойрхон байгаа тул лабораторийн нөөц шалгана уу",
      },
      {
        id: "n-3",
        type: "info",
        text: "5 эссе асуулт багшаар шалгагдах хүлээлттэй",
      },
      {
        id: "n-4",
        type: "info",
        text: "Тусгай заавар: график бодлогод черновик цаас тараана",
      },
    ],
  },
  "exam-202": {
    id: "exam-202",
    title: "Эх бичиг ба найруулга",
    subject: "Монгол хэл",
    status: "ongoing",
    className: "9B",
    teacherName: "О.Наранзул",
    date: "2026-03-28",
    startTime: "11:00",
    endTime: "11:35",
    durationMinutes: 35,
    room: "301",
    examType: "Холимог",
    totalScore: 35,
    studentCount: 41,
    submittedCount: 26,
    notStartedCount: 15,
    questionCount: 18,
    multipleChoiceCount: 12,
    essayCount: 6,
    autoGradedCount: 12,
    manualReviewCount: 6,
    autoGradingStatus: "Явагдаж буй",
    manualGradingStatus: "Эхлээгүй",
    finalResultStatus: "Хүлээгдэж буй",
    notes: [
      {
        id: "n-5",
        type: "warning",
        text: "5 сурагч шалгалтаа хараахан эхлээгүй байна",
      },
      {
        id: "n-6",
        type: "info",
        text: "Хариулт хадгалалтын лог хэвийн ажиллаж байна",
      },
    ],
  },
  "exam-203": {
    id: "exam-203",
    title: "Хүч ба хөдөлгөөн",
    subject: "Физик",
    status: "grading",
    className: "11B",
    teacherName: "С.Тэмүүлэн",
    date: "2026-03-28",
    startTime: "08:30",
    endTime: "09:20",
    durationMinutes: 50,
    room: "Lab-2",
    examType: "Холимог",
    totalScore: 50,
    studentCount: 35,
    submittedCount: 35,
    notStartedCount: 0,
    questionCount: 22,
    multipleChoiceCount: 16,
    essayCount: 6,
    autoGradedCount: 16,
    manualReviewCount: 6,
    autoGradingStatus: "Бэлэн",
    manualGradingStatus: "Хийгдэж буй",
    finalResultStatus: "Ноорог",
    notes: [
      {
        id: "n-7",
        type: "warning",
        text: "6 нээлттэй асуулт багшаар шалгагдаж дуусаагүй байна",
      },
      {
        id: "n-8",
        type: "info",
        text: "Final score publish хийхээс өмнө rubric review шаардлагатай",
      },
    ],
  },
};

export function getExamDetailOrThrow(id: string) {
  const detail = examDetails[id];
  if (!detail) notFound();
  return detail;
}
