import type { Question, StudentExamResult } from "./types";

export const mockQuestions: Question[] = [
  {
    id: "q-001",
    title: "Шулуун функцийн график",
    content: "y = 2x - 3 функцийг графиклаж, налалт ба огтлолцлыг ол.",
    type: "multiple_choice",
    subject: "Математик",
    topic: "Алгебр",
    gradeLevel: "8-р анги",
    difficulty: "Хялбар",
    skillTag: "Цээжлэх",
    usageCount: 28,
    correctRate: 92,
    status: "Идэвхтэй",
    createdBy: "Н. Энхмаа",
    lastUsedAt: "2026-03-20",
    choices: ["m=2, b=-3", "m=-2, b=3", "m=3, b=-2", "m=2, b=3"],
    answerKey: "m=2, b=-3",
  },
  {
    id: "q-002",
    title: "Квадрат тэгшитгэлийн язгуур",
    content: "x² - 7x + 12 = 0 тэгшитгэлийн язгууруудыг ол.",
    type: "short_answer",
    subject: "Математик",
    topic: "Алгебр",
    gradeLevel: "9-р анги",
    difficulty: "Дунд",
    skillTag: "Бодлого бодолт",
    usageCount: 17,
    correctRate: 64,
    status: "Идэвхтэй",
    createdBy: "Н. Энхмаа",
    lastUsedAt: "2026-03-18",
    answerKey: "3,4",
  },
  {
    id: "q-003",
    title: "Ньютоны 2-р хууль",
    content: "F=ma томьёог бодит амьдралын жишээгээр тайлбарла.",
    type: "essay",
    subject: "Физик",
    topic: "Механик",
    gradeLevel: "10-р анги",
    difficulty: "Дунд",
    skillTag: "Шинжилгээ",
    usageCount: 24,
    correctRate: 48,
    status: "Идэвхтэй",
    createdBy: "Б. Түвшин",
    lastUsedAt: "2026-03-16",
  },
  {
    id: "q-004",
    title: "Хүчил-суурийн саармагжих урвал",
    content: "HCl + NaOH урвалын бүтээгдэхүүнийг тодорхойл.",
    type: "multiple_choice",
    subject: "Хими",
    topic: "Урвал",
    gradeLevel: "9-р анги",
    difficulty: "Хялбар",
    skillTag: "Цээжлэх",
    usageCount: 29,
    correctRate: 37,
    status: "Идэвхтэй",
    createdBy: "С. Ариунаа",
    lastUsedAt: "2026-03-15",
    choices: ["NaCl + H2O", "H2 + NaCl", "NaOH + HCl", "Cl2 + H2O"],
    answerKey: "NaCl + H2O",
  },
  {
    id: "q-005",
    title: "Нөхцөлт өгүүлбэр",
    content: "If I ___ time, I would study more. (have/had/has)",
    type: "multiple_choice",
    subject: "Англи хэл",
    topic: "Дүрэм",
    gradeLevel: "9-р анги",
    difficulty: "Хялбар",
    skillTag: "Цээжлэх",
    usageCount: 22,
    correctRate: 84,
    status: "Идэвхтэй",
    createdBy: "Д. Мөнхзул",
    lastUsedAt: "2026-03-17",
    choices: ["have", "had", "has", "having"],
    answerKey: "had",
  },
  {
    id: "q-006",
    title: "Эхийн гол санаа",
    content: "Өгөгдсөн эхээс гол санаа болон дэмжих санаа хоёрыг бич.",
    type: "essay",
    subject: "Монгол хэл",
    topic: "Уншиж ойлгох",
    gradeLevel: "8-р анги",
    difficulty: "Дунд",
    skillTag: "Шинжилгээ",
    usageCount: 11,
    correctRate: 58,
    status: "Идэвхтэй",
    createdBy: "Г. Саруул",
    lastUsedAt: "2026-03-14",
  },
  {
    id: "q-007",
    title: "Фотосинтезийн үндсэн тэгшитгэл",
    content: "Фотосинтезийн урвалын тэгшитгэлийг бич.",
    type: "short_answer",
    subject: "Биологи",
    topic: "Эсийн биологи",
    gradeLevel: "7-р анги",
    difficulty: "Дунд",
    skillTag: "Цээжлэх",
    usageCount: 13,
    correctRate: 66,
    status: "Идэвхтэй",
    createdBy: "П. Халиун",
    lastUsedAt: "2026-03-13",
    answerKey: "6CO2 + 6H2O -> C6H12O6 + 6O2",
  },
  {
    id: "q-008",
    title: "Тригонометрийн харьцаа",
    content: "sin(30°)-ын утгыг сонго.",
    type: "multiple_choice",
    subject: "Математик",
    topic: "Тригонометр",
    gradeLevel: "10-р анги",
    difficulty: "Хялбар",
    skillTag: "Логик",
    usageCount: 20,
    correctRate: 81,
    status: "Идэвхтэй",
    createdBy: "Н. Энхмаа",
    lastUsedAt: "2026-03-12",
    choices: ["1/2", "√3/2", "1", "0"],
    answerKey: "1/2",
  },
  {
    id: "q-009",
    title: "Импульс хадгалагдах хууль",
    content: "Мөргөлдөөний бодлогод импульс хэрхэн хадгалагдахыг тайлбарла.",
    type: "essay",
    subject: "Физик",
    topic: "Импульс",
    gradeLevel: "11-р анги",
    difficulty: "Хэцүү",
    skillTag: "Бодлого бодолт",
    usageCount: 9,
    correctRate: 34,
    status: "Ноорог",
    createdBy: "Б. Түвшин",
    lastUsedAt: "2026-03-10",
  },
  {
    id: "q-010",
    title: "Үгийн утга таах",
    content: "Context ашиглан word meaning тодорхойл.",
    type: "short_answer",
    subject: "Англи хэл",
    topic: "Үгийн сан",
    gradeLevel: "8-р анги",
    difficulty: "Дунд",
    skillTag: "Логик",
    usageCount: 18,
    correctRate: 72,
    status: "Идэвхтэй",
    createdBy: "Д. Мөнхзул",
    lastUsedAt: "2026-03-09",
  },
  {
    id: "q-011",
    title: "Органик ба органик бус",
    content: "Органик болон органик бус нэгдлийн ялгааг жишээгээр тайлбарла.",
    type: "short_answer",
    subject: "Хими",
    topic: "Органик хими",
    gradeLevel: "10-р анги",
    difficulty: "Дунд",
    skillTag: "Шинжилгээ",
    usageCount: 16,
    correctRate: 61,
    status: "Идэвхтэй",
    createdBy: "С. Ариунаа",
    lastUsedAt: "2026-03-08",
  },
  {
    id: "q-012",
    title: "Талбай олох бодлого",
    content: "Өгөгдсөн трапецын талбайг ол.",
    type: "multiple_choice",
    subject: "Математик",
    topic: "Геометр",
    gradeLevel: "7-р анги",
    difficulty: "Хялбар",
    skillTag: "Бодлого бодолт",
    usageCount: 26,
    correctRate: 39,
    status: "Идэвхтэй",
    createdBy: "Н. Энхмаа",
    lastUsedAt: "2026-03-07",
    choices: ["24", "18", "30", "12"],
    answerKey: "24",
  },
  {
    id: "q-013",
    title: "Монгол хэлний найруулга",
    content: "Өгүүлбэрийн найруулгын алдааг олоод зас.",
    type: "short_answer",
    subject: "Монгол хэл",
    topic: "Найруулга",
    gradeLevel: "10-р анги",
    difficulty: "Дунд",
    skillTag: "Логик",
    usageCount: 14,
    correctRate: 68,
    status: "Идэвхтэй",
    createdBy: "Г. Саруул",
    lastUsedAt: "2026-03-06",
  },
  {
    id: "q-014",
    title: "Эсийн бүтэц",
    content: "Эукариот эсийн үндсэн бүтцүүдийг нэрлэ.",
    type: "multiple_choice",
    subject: "Биологи",
    topic: "Эс",
    gradeLevel: "6-р анги",
    difficulty: "Хялбар",
    skillTag: "Цээжлэх",
    usageCount: 12,
    correctRate: 89,
    status: "Идэвхтэй",
    createdBy: "П. Халиун",
    lastUsedAt: "2026-03-05",
    choices: ["Цөм, мембран, цитоплазм", "Элэг, зүрх, уушги", "Электрон, протон", "ДНХ л"],
    answerKey: "Цөм, мембран, цитоплазм",
  },
  {
    id: "q-015",
    title: "Хүч ба хөдөлгөөн",
    content: "Хурдатгал өөрчлөгдөхөд хүч хэрхэн нөлөөлөх вэ?",
    type: "essay",
    subject: "Физик",
    topic: "Динамик",
    gradeLevel: "9-р анги",
    difficulty: "Дунд",
    skillTag: "Шинжилгээ",
    usageCount: 21,
    correctRate: 45,
    status: "Архивласан",
    createdBy: "Б. Түвшин",
    lastUsedAt: "2026-03-04",
  },
  {
    id: "q-016",
    title: "Нөхцөлт өгүүлбэр II",
    content: "If she ___ earlier, she would catch the bus.",
    type: "multiple_choice",
    subject: "Англи хэл",
    topic: "Дүрэм",
    gradeLevel: "9-р анги",
    difficulty: "Хялбар",
    skillTag: "Цээжлэх",
    usageCount: 23,
    correctRate: 91,
    status: "Идэвхтэй",
    createdBy: "Д. Мөнхзул",
    lastUsedAt: "2026-03-03",
    choices: ["wake", "woke", "had woken", "wakes"],
    answerKey: "had woken",
  },
  {
    id: "q-017",
    title: "Магадлалын бодлого",
    content: "2 улаан, 3 цэнхэр бөмбөгнөөс улаан авах магадлал хэд вэ?",
    type: "short_answer",
    subject: "Математик",
    topic: "Магадлал",
    gradeLevel: "11-р анги",
    difficulty: "Хэцүү",
    skillTag: "Логик",
    usageCount: 15,
    correctRate: 51,
    status: "Идэвхтэй",
    createdBy: "Н. Энхмаа",
    lastUsedAt: "2026-03-02",
    answerKey: "2/5",
  },
  {
    id: "q-018",
    title: "Исэлдэн ангижрах урвал",
    content: "Өгөгдсөн урвалаас исэлдэгч ба ангижруулагчийг тодорхойл.",
    type: "essay",
    subject: "Хими",
    topic: "Исэлдэн ангижрах",
    gradeLevel: "11-р анги",
    difficulty: "Хэцүү",
    skillTag: "Шинжилгээ",
    usageCount: 8,
    correctRate: 42,
    status: "Ноорог",
    createdBy: "С. Ариунаа",
    lastUsedAt: "2026-03-01",
  },
  {
    id: "q-019",
    title: "Өгүүлбэр задлан шинжлэх",
    content: "Нийлмэл өгүүлбэрийг өгүүлбэр зүйн хувьд задлан шинжил.",
    type: "essay",
    subject: "Монгол хэл",
    topic: "Өгүүлбэр зүй",
    gradeLevel: "11-р анги",
    difficulty: "Хэцүү",
    skillTag: "Шинжилгээ",
    usageCount: 7,
    correctRate: 47,
    status: "Идэвхтэй",
    createdBy: "Г. Саруул",
    lastUsedAt: "2026-02-28",
  },
  {
    id: "q-020",
    title: "Удамшлын бодлого",
    content: "Гетерозигот хослолоос гарах генотипийн харьцааг ол.",
    type: "short_answer",
    subject: "Биологи",
    topic: "Генетик",
    gradeLevel: "12-р анги",
    difficulty: "Хэцүү",
    skillTag: "Бодлого бодолт",
    usageCount: 6,
    correctRate: 33,
    status: "Идэвхтэй",
    createdBy: "П. Халиун",
    lastUsedAt: "2026-02-27",
  },
];

export const mockStudentResults: StudentExamResult[] = [
  {
    studentName: "Батбаяр Доржсүрэн",
    score: 16,
    maxScore: 20,
    status: "Илгээсэн",
    submittedAt: "2026-03-20 18:30",
  },
  {
    studentName: "Сарангэрэл Энхбат",
    score: 9,
    maxScore: 20,
    status: "Илгээсэн",
    submittedAt: "2026-03-20 18:42",
  },
  {
    studentName: "Элзий-Орших Түвшин",
    score: 14,
    maxScore: 20,
    status: "Илгээсэн",
    submittedAt: "2026-03-20 18:46",
  },
  {
    studentName: "Мөнхзул Баттулга",
    score: 0,
    maxScore: 20,
    status: "Хүлээгдэж буй",
    submittedAt: "-",
  },
];
